import { createServer, type IncomingMessage, type Server, type ServerResponse } from 'node:http';
import { timingSafeEqual } from 'node:crypto';
import { redactSecrets } from '@bench/core';

/**
 * Liveness for the worker.
 *
 * The worker is a set of timers, not a request handler, so it has no port of
 * its own and a host has no way to tell a process that is quietly wedged from
 * one that is working. This adds the smallest thing that answers that: a JSON
 * endpoint reporting when each queue last completed a tick.
 *
 * It reports and does not judge. Returning 503 when a queue looks stale sounds
 * stricter, and would be wrong here: the cadences differ by three orders of
 * magnitude - the indexer ticks every 30s, auditions hourly - so any single
 * staleness threshold either never fires or restarts a healthy worker in the
 * gap between two audition runs. A restart loop is worse than a slow queue,
 * and the ages are in the body for a human or an alert to read.
 */
/**
 * What a completed tick achieved.
 *
 * Three states, not two, because "did nothing" covers two opposite situations.
 * A prober with every endpoint probed inside the last hour and an audition
 * queue whose whole verified-live set is inside the re-audition floor are both
 * doing exactly what they are supposed to; a scorer that cannot see the agent
 * it is meant to score is not. Collapsing them made the status page report
 * "needs attention" on a healthy worker, which is how an alert that had just
 * found three real bugs starts getting ignored.
 *
 * - `worked`: the tick produced output.
 * - `nothing-due`: the schedule legitimately had nothing for it.
 * - `idle`: it had candidates it neither handled nor accounted for. This is
 *   the shape every one of those bugs took, and the only one that alerts.
 */
export type TickOutcome = 'worked' | 'nothing-due' | 'idle';

export interface Heartbeat {
  mark(queue: string, result?: string, outcome?: TickOutcome): void;
  fail(queue: string, reason?: string): void;
}

interface QueueState {
  lastOkAt: number | null;
  lastFailAt: number | null;
  ticks: number;
  failures: number;
  /**
   * Why the last failure failed.
   *
   * Counting failures says a queue is broken and nothing about what to do -
   * and on a hosted worker the logs are a click away from whoever is looking
   * at this endpoint, which in practice means the reason is not read. A queue
   * that has failed twice and cannot say why is a queue nobody can fix from
   * here.
   */
  lastFailReason: string | null;
  /**
   * What the last successful tick actually did.
   *
   * A tick that succeeds and accomplishes nothing is indistinguishable here
   * from one that did the work - the audition queue ran forty times, reported
   * zero failures, and auditioned no agent, and the counters said everything
   * was fine. "Succeeded" is not an outcome; it is the absence of an error.
   */
  lastResult: string | null;
}

/**
 * Consecutive unaccounted-for ticks before a queue is called out. Counts only
 * `idle`, so a caught-up prober or audition queue never reaches it however
 * long it stays quiet.
 */
const IDLE_STREAK_ALERT = 5;

/**
 * Shared secret required to read the queue detail, when one is configured.
 *
 * Without it this endpoint served queue names, uptime and - the part that
 * mattered - the last failure message of every queue, to anyone. Those
 * messages are generated by libraries that put connection strings in them, so
 * the endpoint was a credential disclosure waiting for one RPC hiccup.
 *
 * Two levels rather than all-or-nothing: an unauthenticated caller still gets
 * status and uptime, because a host healthcheck has to work without holding a
 * secret, and because the public status page is a genuine product feature. The
 * per-queue detail needs the token.
 */
function healthToken(): string | undefined {
  // Read per request rather than at module load. A module-level read cannot be
  // exercised by a test that sets the variable afterwards, and an unreachable
  // branch in an authorization check is the one place that is not acceptable.
  const t = process.env['BENCH_WORKER_HEALTH_TOKEN'];
  return t === undefined || t === '' ? undefined : t;
}

function authorized(req: { headers: Record<string, unknown>; url?: string | undefined }): boolean {
  const expected = healthToken();
  if (expected === undefined) return false;

  const header = req.headers['authorization'];
  const bearer = typeof header === 'string' ? header.replace(/^Bearer\s+/i, '') : '';
  // Also accepted as a query parameter, because the web app's fetch is
  // configured with a single URL and Vercel env vars are strings, not headers.
  const fromQuery = ((): string => {
    try {
      return new URL(req.url ?? '/', 'http://localhost').searchParams.get('token') ?? '';
    } catch {
      return '';
    }
  })();

  const given = bearer !== '' ? bearer : fromQuery;
  const a = Buffer.from(given);
  const b = Buffer.from(expected);
  return a.length === b.length && timingSafeEqual(a, b);
}

/**
 * Something else that wants requests on this port.
 *
 * The worker gets one public port from its host, and the audition gateway
 * needs it too - a fork's RPC has to be reachable by an agent that is not on
 * this machine. Returning true means the request was handled.
 */
export type ExtraHandler = (
  req: IncomingMessage,
  res: ServerResponse,
) => boolean | Promise<boolean>;

export function startHealthServer(
  port: number,
  extra?: ExtraHandler,
): { heartbeat: Heartbeat; server: Server } {
  const startedAt = Date.now();
  const queues = new Map<string, QueueState>();
  const stateFor = (q: string): QueueState => {
    let s = queues.get(q);
    if (s === undefined) {
      s = {
        lastOkAt: null,
        lastFailAt: null,
        ticks: 0,
        failures: 0,
        lastFailReason: null,
        lastResult: null,
      };
      queues.set(q, s);
    }
    return s;
  };

  const heartbeat: Heartbeat = {
    mark(queue, result, outcome) {
      const s = stateFor(queue);
      s.lastOkAt = Date.now();
      s.ticks += 1;
      if (result !== undefined) s.lastResult = redactSecrets(result);
      // Only tracked when the caller classifies the tick. A queue that cannot
      // answer is left out rather than assumed busy.
      if (outcome === 'idle') idleStreak.set(queue, (idleStreak.get(queue) ?? 0) + 1);
      else if (outcome !== undefined) idleStreak.set(queue, 0);
    },
    fail(queue, reason) {
      const s = stateFor(queue);
      s.lastFailAt = Date.now();
      s.failures += 1;
      // Redacted and bounded here as well as at the call site. A caller that
      // forgets is the normal way a secret gets published, and this is the one
      // place every failure passes through.
      s.lastFailReason = reason === undefined ? null : redactSecrets(reason);
    },
  };

  /**
   * How many consecutive ticks a queue has completed with work it could not
   * account for.
   *
   * The audition queue ran forty times, reported zero failures, and auditioned
   * no agent. Nothing was red; the queue was succeeding at nothing, and no
   * counter here could tell that from working. "Succeeded" is the absence of an
   * error, not an outcome - so a queue that keeps completing without effect is
   * visible as `idleStreak`, and the endpoint says overall that something needs
   * looking at. Ticks the queue can explain do not count: see `TickOutcome`.
   */
  const idleStreak = new Map<string, number>();

  const server = createServer((req, res) => {
    if (extra !== undefined) {
      void (async () => {
        try {
          if (await extra(req, res)) return;
        } catch {
          if (!res.headersSent) {
            res.writeHead(500, { 'content-type': 'application/json' });
            res.end('{"error":"handler failed"}');
          }
          return;
        }
        respondHealth(req, res);
      })();
      return;
    }
    respondHealth(req, res);
  });

  function respondHealth(req: IncomingMessage, res: ServerResponse): void {
    const now = Date.now();
    const detailed = authorized(req);
    const stalled = [...idleStreak.entries()].filter(([, n]) => n >= IDLE_STREAK_ALERT);
    const body = {
      status: stalled.length === 0 ? 'up' : 'degraded',
      // Named, not just counted: whoever reads this needs to know which queue.
      ...(stalled.length === 0
        ? {}
        : {
            attention: stalled.map(
              ([q, n]) =>
                `${q} has completed ${n} consecutive ticks with work it did not account for`,
            ),
          }),
      uptimeSeconds: Math.round((now - startedAt) / 1000),
      // Set when the caller could not prove it should see queue detail, so a
      // reader can tell "nothing is running" from "you were not shown it".
      ...(detailed ? {} : { detail: 'withheld' as const }),
      queues: detailed
        ? Object.fromEntries(
            [...queues.entries()].map(([name, s]) => [
              name,
              {
                ticks: s.ticks,
                failures: s.failures,
                secondsSinceLastOk:
                  s.lastOkAt === null ? null : Math.round((now - s.lastOkAt) / 1000),
                secondsSinceLastFailure:
                  s.lastFailAt === null ? null : Math.round((now - s.lastFailAt) / 1000),
                lastFailure: s.lastFailReason,
                lastResult: s.lastResult,
                idleStreak: idleStreak.get(name) ?? 0,
              },
            ]),
          )
        : {},
    };
    res.writeHead(200, { 'content-type': 'application/json' });
    res.end(JSON.stringify(body, null, 2));
    // Every path that is not claimed above answers the same thing, so a host
    // configured to check `/` and one configured to check `/health` both work.
  }

  // A port already in use is a local-development annoyance, not a reason to
  // ground the worker - the queues are the product, this is instrumentation.
  server.on('error', (err: NodeJS.ErrnoException) => {
    console.error(`[bench:worker] health server not listening (${err.code ?? err.message})`);
  });
  server.listen(port, () => {
    console.log(`[bench:worker] health on :${port}`);
  });
  // Do not let an idle health socket hold the process open during shutdown.
  server.unref();

  return { heartbeat, server };
}
